cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.pyenv
dist: xenial
env:
  global:
  - HOMEBREW_NO_AUTO_UPDATE=1
  - PYENV_ROOT="$HOME/.pyenv"
  - PATH="$PYENV_ROOT/bin:$PATH"
  - PIP_CACHE_DIR="$HOME/.cache/pip"
stages:
- check
- test
- build
jobs:
  include:
  - name: Check patch formatting
    stage: check
    os: linux
    language: python
    python: 3.7
    before_install: null
    install: null
    script: ./scripts/ci/check_patch.sh
  - name: 3.7 on Windows
    stage: test
    os: windows
    language: shell
    env:
    - PYTHON_VERSION=3.7.5
    - PATH=/c/Python37:/c/Python37/Scripts:$PATH
  - name: 3.8 on Windows
    os: windows
    language: shell
    env:
    - PYTHON_VERSION=3.8.0
    - PATH=/c/Python38:/c/Python38/Scripts:$PATH
  - name: 3.5 on Linux
    language: python
    python: 3.5
  - name: 3.6 on Linux
    language: python
    python: 3.6
  - name: 3.7 on Linux
    language: python
    python: 3.7
  - name: 3.8 on Linux
    language: python
    python: 3.8
  - name: 3.7 on Mac
    os: osx
    osx_image: xcode11.3
  - name: Mac pkg
    stage: build
    os: osx
    osx_image: xcode9.4
    language: ruby
    rvm: 2.4.3
    install: null
    script: ./scripts/build_posix.sh
  - name: Windows pkg
    os: windows
    language: shell
    install: null
    script: ./scripts/build_windows.cmd
    env:
    - PYTHON_VERSION=3.7.5
    - PATH=/c/Python37:/c/Python37/Scripts:$PATH
  - name: Linux pkgs
    language: python
    python: 3.7
    before_install: null
    install: null
    script: ./scripts/build_posix.sh
  - name: PyPI pkgs
    language: python
    python: 3.8
    script: ./scripts/build_package.sh
  - name: Snapcraft snap
    language: python
    python: 3.8
    addons:
      snaps:
      - name: snapcraft
        channel: stable
        confinement: classic
      - name: review-tools
        channel: stable
      - name: lxd
        channel: stable
    env:
    - SNAPCRAFT_IMAGE_INFO: '{"build_url": "$TRAVIS_BUILD_URL"}'
    install:
    - sudo /snap/bin/lxd.migrate -yes
    - sudo /snap/bin/lxd waitready
    - sudo /snap/bin/lxd init --auto
    script:
    - ./scripts/build_snap.sh
    after_failure:
    - sudo journalctl -u snapd
before_install:
- bash ./scripts/ci/before_install.sh
- source env.sh
- bash ./scripts/ci/check_python.sh
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
install:
- bash ./scripts/ci/install.sh
before_script:
- bash test_mypy.sh
script:
- echo "SCRIPT SECTION"
